### PR TITLE
Added good experiment table books - Maybe soon-ish 

### PR DESCRIPTION
**Pull request by j10a1n15**
Problem is, that the book stats is not in some hidden data, but only in the lore

### CODE REVIEW

**Comment by j10a1n15** [comment]
Todo: serum, maybe ogher Rng Drops?

**Comment by Su386yt** [comment]
why don't you just use the average price

**Comment by j10a1n15** [comment]
Wdym average price

**Comment by Su386yt** [comment]
Well instead of listing the valuable items, you can just get the price of the item and see if it's above a threshold

**Comment by j10a1n15** [comment]
So I would have to translate the from the ore to the item, and then check its lb

**Comment by Su386yt** [comment]
What

**Comment by j10a1n15** [comment]
The item in the table is not a normal enchanted book

**Comment by j10a1n15** [comment]
Its just some book item with lore on what enchant the book has, no special attriutes hidden

**Comment by j10a1n15** [comment]
Here, this is the nbt data of a enchanted book in the experiment table:
```json
{
    id: "minecraft:glowstone",
    Count: 2b,
    tag: {
        overrideMeta: 1b,
        display: {
            Lore: ["§8Item Reward", "", "§9Chance II", "§7Increases the chance of a", "§7Monster dropping an item by", "§7§a30%§7."],
            Name: "§fEnchanted Book"
        },
        AttributeModifiers: []
    },
    Damage: 0s
}
```

This is the lore of a real enchanted book:
```json
{
    id: "minecraft:enchanted_book",
    Count: 1b,
    tag: {
        ench: [],
        HideFlags: 254,
        display: {
            Lore: ["§9Rejuvenate V", "§7Grants §c+10❣ Health Regen§7.", "", "§7§7Apply Cost: §350 Exp Levels", "", "§7Applicable on: §9Armor", "§7Use this on an item in an Anvil", "§7to apply it!", "", "§a§lUNCOMMON"],
            Name: "§aEnchanted Book"
        },
        ExtraAttributes: {
            id: "ENCHANTED_BOOK",
            enchantments: {
                rejuvenate: 5
            },
            uuid: "57897b56-fbc6-4132-9329-57e33900c47d",
            timestamp: "10/12/23 12:28 PM"
        }
    },
    Damage: 0s
}
```



The table "book" is missing the extra attribute which basically says what kind of enchant it is,
thats why need to filter the item lore and compare it with this list

**Comment by Su386yt** [comment]
You can take first line of the book and look it up with SkyblockDataManager (theres a name to id map)

**Comment by j10a1n15** [comment]
Sounds fancy, will do that whenever I do that feature
But gonna do smth else first

**Pull request merged**
