### PR TITLE
Added a ton of mods to mods.json

### PR DESCRIPTION
**Pull request by Su386yt**

### CODE REVIEW

**Review by j10a1n15 — COMMENTED** [review]
I love the LOCALE versions

**Comment by Su386yt** [comment]
Geniunely, that's what it's called in the mod

**Comment by Su386yt** [comment]
I opened the mod up in 7zip to check

**Comment by Su386yt** [comment]
Merge whenever

**Comment by j10a1n15** [comment]
> Geniunely, that's what it's called in the mod

wtf why

**Comment by j10a1n15** [comment]
> Merge whenever

you gotta, dont have write access

**Comment by Su386yt** [comment]
> > Merge whenever
> 
> you gotta, dont have write access

I'll fix that later (when I have my phone next to me for 2fa)

**Pull request merged**
