### PR TITLE
add missing things in booster_cookie_price.json

### PR DESCRIPTION
**Pull request by RayDeeUx**

### CODE REVIEW

**Review by j10a1n15 — APPROVED** [review]
[208] ᛝ [MVP+] Erymanthus: hello yes PSS repo pr merge pls

**Comment by j10a1n15** [comment]
Nvm still dont have write access oops

**Comment by j10a1n15** [comment]
image

**Comment by RayDeeUx** [comment]
wait what

**Comment by RayDeeUx** [comment]
welp time to wait for su

**Pull request merged**
